### PR TITLE
local dev instructions added to README

### PR DESCRIPTION
**Pull request by bk521234**

### CODE REVIEW

**Comment by mwt** [comment]
Helpful!

As someone unfamiliar with Heroku, I had been been directly running:
```{bash}
​gunicorn main-mod:app --log-file -
```

**Comment by bk521234** [comment]
@MattWThomas oh yeah, that'd be another option if people didn't want to download the heroku cli. I think both options could help people get up and running as fast as possible.

we should add that option too?

**Comment by meg-ray** [comment]
@bk521234 - This is a super helpful addition to the documentation for contributors. I do think that we should add gunicorn suggestion from @MattWThomas. If we are going to be complete and accessible to newer contributors, we should probably also include using `flask run` directly.

**Comment by mwt** [comment]
@meg-ray `flask run` actually failed for me. Does it work for you?

**Comment by meg-ray** [comment]
@MattWThomas Yes, it works for me, but it's probably a bit clunky due to the way things are named and organized.  I will open a new ticket about cleaning up the naming conventions. Let's go ahead and add the documentation about using Heroku cli and gunicorn and we can add in the `flask run` documentation, once it's been cleaned up a bit.

**Comment by bk521234** [comment]
sounds good! will do

**Comment by meg-ray** [comment]
Thank you, @bk521234 This is great.

**Pull request merged**
